name: tvax 
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python>=3.5
  - bioconda::hyphy==2.5.41
  - bioconda::iqtree==2.2.0.3
  - bioconda::mafft==7.505
  - pip:
    - -r requirements.txt